name: 📕 Docs

on:
  push:
    branches:
      - master

  pull_request:

  release:
    types: [published]

  workflow_dispatch:

jobs:

  build_and_publish_documentation:

    name: Build and publish documentation
    runs-on: ubuntu-latest

    defaults:
      run:
        shell: bash -l {0}

    steps:

      - name: Checkout code
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Set up Python 3.9
        uses: actions/setup-python@v2
        with:
          python-version: 3.9

      - name: Install
        run: |
          python -m pip install git+https://github.com/spectrochempy/spectrochempy.git
          python -m pip install sphinx_rtd_theme
          python -m pip install sphinx
          python -m pip install nbsphinx
          python -m pip install sphinx_copybutton
          sudo apt-get update
          sudo apt-get install pandoc

      - name: Build docs
        run: |
          mkdir -p build

          echo "cloning gh-pages repository"
          git clone --branch=gh_pages --single-branch https://github.com/spectrochempy/spectrochempy-tutorials.git build/html

          echo "Recreating docs"
          make html

      - name: Deployment
        if: (github.event_name != 'pull_request')
        uses: JamesIves/github-pages-deploy-action@4.1.5
        with:
          branch: gh_pages
          folder: build/html/
          single-commit: true
